name: Trigger auto deployment for classification-api

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/classification-api-AutoDeployTrigger-b47a25b8-f533-4630-8ee2-c6ee64e341bf.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CLASSIFICATIONAPI_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CLASSIFICATIONAPI_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CLASSIFICATIONAPI_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: 
          registryUsername: ${{ secrets.CLASSIFICATIONAPI_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CLASSIFICATIONAPI_REGISTRY_PASSWORD }}
          containerAppName: classification-api
          resourceGroup: Stress_Detection_Project
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


